# Generated by Django 4.0.6 on 2022-08-13 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.imagealbum', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='videoalbum',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.videoalbum', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='path',
            field=models.FileField(upload_to='uploads', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
