# Generated by Django 4.0.6 on 2022-08-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_album_alter_image_path_alter_image_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'Фотоальбом'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
        migrations.AlterModelOptions(
            name='videoalbum',
            options={'verbose_name': 'Видеоальбом'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'verbose_name': 'Видео'},
        ),
    ]
