# Generated by Django 4.0.6 on 2022-08-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_image_options_alter_imagealbum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбом'},
        ),
        migrations.AlterModelOptions(
            name='videoalbum',
            options={'verbose_name': 'Видеоальбом', 'verbose_name_plural': 'Видеоальбом'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
