# Generated by Django 4.0.6 on 2022-08-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_options_alter_imagealbum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название фото'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название видео'),
        ),
    ]
