# Generated by Django 4.0.6 on 2022-08-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_title_alter_videofile_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбомы'},
        ),
        migrations.AlterModelOptions(
            name='videoalbum',
            options={'verbose_name': 'Видеоальбом', 'verbose_name_plural': 'Видеоальбомы'},
        ),
    ]
